title: Eugene's blog
description: Living, Loving and Learning
show_downloads: true

baseurl:  # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "http://www.eugenepark.net" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: eugenepark
image: /thumbnail-jumbo.png
twitter:
  username: eugenepark7676
github:
  owner_url: parkeugene  

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['about']
